version: '2'
services:
  signer01-bootstrap:
    build: geth-client
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --syncmode "full" --networkid=161616 --port 30321 --nodekeyhex "091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322" --rpc --rpcaddr="0.0.0.0" --rpcapi "db,personal,eth,net,web3,txpool,miner,admin,clique" --rpccorsdomain="*" -unlock "1c203dca73df132398c511451be9b0f9a28f4b59" --password /root/files/password/password.txt --mine'
    volumes:
      - ./files/accounts/signer01/keystore:/root/.ethereum/devchain/keystore:rw
      - ./files/accounts/signer01/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/localtime:/etc/localtime:ro
    ports:
      - "30321:30321"
      - "30321:30321/udp"
      - "8545:8545"
  signer02:
    build: geth-client
    restart: on-failure
    links:
      - signer01-bootstrap
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/accounts/signer02/keystore:/root/.ethereum/devchain/keystore:rw
      - ./files/accounts/signer02/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain --syncmode "full" --networkid=161616 --port 30322 --rpc --rpccorsdomain="*" --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30321" -unlock "08be2e527bc17471566cf71080b537e051916139" --password /root/files/password/password.txt --mine'
  member01:
    build: geth-client
    restart: on-failure
    links:
      - signer01-bootstrap
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/accounts/member01/keystore:/root/.ethereum/devchain/keystore:rw
      - ./files/accounts/member01/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain --syncmode "full" --networkid=161616 --port 30323 --rpc --rpccorsdomain="*" --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30321"'
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - ./files/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
  explorer:
    build: explorer
    restart: on-failure
    container_name: explorer
    volumes:
      - ./files/localtime:/etc/localtime:ro
    ports:
      - "8000:8000"
